name: RandomLoot
version: '${project.version}'
main: org.nathanlovette.randomloot.RandomLoot
api-version: 1.19
commands:
  randomloot:
    description: Creates a chest at <x> <y> <z> coordinates containing <item> of a random amount between <minimumAmount> and <maximumAmount>
    usage: /<command> <x> <y> <z> <item> <minimumAmount> <maximumAmount>
    permission: randomloot.randomloot
  randomlootmenu:
    description: Opens the RandomLoot menu
    usage: /<command>
    permission: randomloot.randomloot
  randomlootobj:
    description: Executes the randomloot using the object string given by /randomlootmenu
    usage: /<command> <objectString>
    permission: randomloot.randomloot